{
    "network": {
        "dhcp_enabled": true,  // Set to true to use DHCP, false to always use static IP
        "mac": [2, 0, 0, 0, 0, 1],  // Ensure each device has a unique MAC address
        "ip": [192, 168, 50, 100],  // Static IP configuration
        "subnet": [255, 255, 255, 0],
        "gateway": [192, 168, 50, 1],
        "dns": [8, 8, 8, 8]
    },
    "postgresql": {
        "url": "http://your_postgrest_server_endpoint/power_data"
    },
    "device": {
        "device_id": "monitor_01",
        "location": "office"
    }
}
